# Generated by Django 5.1.7 on 2025-04-27 18:32

import backend.base.const
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('return_schedule', models.JSONField()),
            ],
            options={
                'db_table': 'credit_creditrequest',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=backend.base.const.TransactionType.choices, max_length=7)),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'credit_transaction',
            },
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.RemoveField(
            model_name='creditplan',
            name='bet',
        ),
        migrations.AddField(
            model_name='creditplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(0.9999)]),
        ),
        migrations.AddField(
            model_name='creditplan',
            name='rate_frequency',
            field=models.CharField(choices=[('Day', 'day'), ('Month', 'month'), ('Quarter', 'quarter'), ('Year', 'year')], default='year', max_length=10),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit.creditplan'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
