# Generated by Django 5.1.7 on 2025-05-13 15:05

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_creditrequest_transaction_delete_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='repayment_period_duration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='repayment_period_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='repayment_period_unit',
            field=models.CharField(choices=[('Day', 'day'), ('Month', 'month'), ('Quarter', 'quarter'), ('Year', 'year')], default='year', max_length=10),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
