# Generated by Django 5.1.7 on 2025-05-13 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditrequest_repayment_period_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='repayment_period_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
