# Generated by Django 5.2.1 on 2025-05-22 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_alter_creditrequest_repayment_period_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.9999)]),
        ),
        migrations.AlterField(
            model_name='creditplan',
            name='rate_frequency',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Year', 'Year')], default='year', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditplan',
            name='type',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('Purpose', 'Purpose')], max_length=50),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='repayment_period_unit',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Year', 'Year')], default='year', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
