# Generated by Django 5.1.7 on 2025-03-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[("User", "user"), ("Operator", "operator"), ("Creditor", "creditor")],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                )
            ],
            options={"db_table": "auth_role"},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="users", to="authorize.role"
                    ),
                ),
            ],
            options={"db_table": "auth_user"},
        ),
    ]
