# Generated by Django 5.1.7 on 2025-04-27 18:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insolvency_probability',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(0.9999)]),
        ),
    ]
