# Generated by Django 5.2.1 on 2025-05-22 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_user_insolvency_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insolvency_probability',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.9999)]),
        ),
    ]
